FROM node:20.19.1-alpine3.21
WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY --chown=node:node package*.json ./
RUN npm ci

RUN chown -R node:node /app

EXPOSE 3000

ENV NEXT_PUBLIC_API_URL=/api
ENV BACKEND_URL=http://backend:3001
ENV HOSTNAME=0.0.0.0

USER node

CMD ["node_modules/.bin/next", "dev", "--turbo", "--hostname", "0.0.0.0"]
