FROM node:20.19.1-alpine3.21
WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 3000

RUN npm run build

ENV HOSTNAME=0.0.0.0
CMD ["node_modules/.bin/next", "start", "--hostname", "0.0.0.0"]
