FROM node:20.19.1-alpine3.21
WORKDIR /app

RUN apk add --no-cache openssl libc6-compat

COPY package*.json ./
RUN npm ci

COPY . .

RUN NODE_TLS_REJECT_UNAUTHORIZED=0 npm run prisma:generate

CMD ["sh", "-c", "npx prisma migrate deploy && npm run start:dev"]
