FROM node:20.19.1-alpine3.21
WORKDIR /app

RUN apk add --no-cache openssl libc6-compat ca-certificates

COPY --chown=node:node package*.json ./
RUN npm ci --ignore-scripts

COPY --chown=node:node . .

RUN npm run prisma:generate

RUN chown -R node:node /app

USER node

CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run start:dev"]
